name: HACombiner CameraTools Core (OLD REPO)
version: "1.0"
slug: HAC_CTC_OLD
description: "HACombiner's CameraTools Core Addon."
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
options: {}
schema: {}
