name: HACombiner CameraTools Core
version: "1.0"
slug: HAC_CTC
description: "HACombiner's CameraTools Core Addon."
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: application
boot: auto
options: {}
schema: {}
