name: Upstream Add-on Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sync go2rtc add-on from AlexxIT
        run: |
          rm -rf go2rtc
          git clone --depth=1 https://github.com/AlexxIT/hassio-addons tmp
          mv tmp/go2rtc go2rtc || (echo "go2rtc folder not found!" && exit 1)
          rm -rf tmp

      - name: Sync rtsp-to-web add-on from Allen Porter
        run: |
          rm -rf rtsp-to-web
          git clone --depth=1 https://github.com/allenporter/stream-addons tmp
          mv tmp/rtsp-to-web rtsp-to-web || (echo "rtsp-to-web folder not found!" && exit 1)
          rm -rf tmp

      - name: Sync rtsp-to-webrtc add-on from Allen Porter
        run: |
          rm -rf rtsp-to-webrtc
          git clone --depth=1 https://github.com/allenporter/stream-addons tmp
          mv tmp/rtsp-to-webrtc rtsp-to-webrtc || (echo "rtsp-to-webrtc folder not found!" && exit 1)
          rm -rf tmp

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git checkout -b upstream-update-$(date +%s)
            git add .
            git commit -m "Update add-ons from upstream"
            git push -u origin HEAD
          else
            echo "No changes detected"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: upstream-auto-update
          title: "Update add-ons from upstream"
          body: "Automated sync of upstream Home Assistant add-ons"
          labels: automated-pr
          draft: false
