name: Sync Add-ons Without Git CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  sync-addons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch go2rtc addon files from AlexxIT
        uses: actions/github-script@v6
        id: fetch_go2rtc
        with:
          script: |
            const files = [
              'config.yaml',
              'README.md',
              'Dockerfile',
              // add other files you want here
            ];
            const baseUrl = 'https://raw.githubusercontent.com/AlexxIT/hassio-addons/main/go2rtc/';
            const fs = require('fs');
            for (const file of files) {
              const url = baseUrl + file;
              const res = await fetch(url);
              if (!res.ok) throw new Error(`Failed to fetch ${url}`);
              const content = await res.text();
              fs.mkdirSync('go2rtc', {recursive: true});
              fs.writeFileSync(`go2rtc/${file}`, content);
            }

      - name: Fetch rtsp-to-web addon files from Allen Porter
        uses: actions/github-script@v6
        id: fetch_rtsp_web
        with:
          script: |
            const files = [
              'config.yaml',
              'README.md',
              'Dockerfile',
              // add other files here
            ];
            const baseUrl = 'https://raw.githubusercontent.com/allenporter/stream-addons/main/rtsp-to-web/';
            const fs = require('fs');
            for (const file of files) {
              const url = baseUrl + file;
              const res = await fetch(url);
              if (!res.ok) throw new Error(`Failed to fetch ${url}`);
              const content = await res.text();
              fs.mkdirSync('rtsp-to-web', {recursive: true});
              fs.writeFileSync(`rtsp-to-web/${file}`, content);
            }

      # Repeat for rtsp-to-webrtc similarly...

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'Update add-ons from upstream repos'
          branch: upstream-auto-update
          title: 'Automated sync of Home Assistant add-ons'
          body: |
            This PR was created automatically by syncing upstream addon files.
          labels: automated-pr
